# Generated by Django 2.0 on 2018-04-26 02:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('openning', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('previous_close', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('volume', models.IntegerField()),
                ('pe_ratio', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('eps', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('one_year', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('full_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('long', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
            ],
        ),
    ]
